/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



package Praktek;

/**
 *
 * @author User
 */
public class cariDeret extends javax.swing.JFrame {

    /**
     * Creates new form cariDeret
     */
    public cariDeret() {
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bilAsli1 = new javax.swing.JTextField();
        bilAsli2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAsli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textAreaAsli = new javax.swing.JScrollPane();
        isiTextAreaAsli = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnGenap = new javax.swing.JButton();
        bilGenap2 = new javax.swing.JTextField();
        isiTextAreaGenap = new javax.swing.JScrollPane();
        jTextAreaGenap = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        bilGenap1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGanjil = new javax.swing.JButton();
        bilGanjil2 = new javax.swing.JTextField();
        textAreaGanjil = new javax.swing.JScrollPane();
        isiTextAreaGanjil = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        bilGanjil1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bilAsli1.setText("0");

        bilAsli2.setText("0");

        jLabel1.setText("s.d.");

        btnAsli.setText("Cari");
        btnAsli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsliActionPerformed(evt);
            }
        });

        jLabel2.setText("Deret Bilangan Asli :");
        jLabel2.setToolTipText("");

        textAreaAsli.setAutoscrolls(true);
        textAreaAsli.setHorizontalScrollBar(null);

        isiTextAreaAsli.setColumns(20);
        isiTextAreaAsli.setRows(5);
        isiTextAreaAsli.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                isiTextAreaAsliInputMethodTextChanged(evt);
            }
        });
        textAreaAsli.setViewportView(isiTextAreaAsli);

        jLabel3.setText("Deret Bilangan Genap :");
        jLabel3.setToolTipText("");

        btnGenap.setText("Cari");
        btnGenap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenapActionPerformed(evt);
            }
        });

        bilGenap2.setText("0");
        bilGenap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilGenap2ActionPerformed(evt);
            }
        });

        jTextAreaGenap.setColumns(20);
        jTextAreaGenap.setRows(5);
        isiTextAreaGenap.setViewportView(jTextAreaGenap);

        jLabel4.setText("s.d.");

        bilGenap1.setText("0");
        bilGenap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilGenap1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Deret Bilangan Ganjil :");
        jLabel5.setToolTipText("");

        btnGanjil.setText("Cari");
        btnGanjil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanjilActionPerformed(evt);
            }
        });

        bilGanjil2.setText("0");

        isiTextAreaGanjil.setColumns(20);
        isiTextAreaGanjil.setRows(5);
        textAreaGanjil.setViewportView(isiTextAreaGanjil);

        jLabel6.setText("s.d.");

        bilGanjil1.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bilGanjil1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bilGanjil2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGanjil))
                    .addComponent(textAreaGanjil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textAreaAsli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bilAsli1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bilAsli2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsli))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(isiTextAreaGenap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bilGenap1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bilGenap2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenap)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilAsli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilAsli2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAsli))
                .addGap(18, 18, 18)
                .addComponent(textAreaAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilGenap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilGenap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnGenap))
                .addGap(18, 18, 18)
                .addComponent(isiTextAreaGenap, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilGanjil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilGanjil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnGanjil))
                .addGap(18, 18, 18)
                .addComponent(textAreaGanjil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsliActionPerformed
        // TODO add your handling code here:
        
      int awal = 100;
      int akhir = 10;
      
      if(awal<akhir)
      {
          int temp = awal;
          awal = akhir;
          akhir = temp;
             
              }
      
      
      
      //bersihkan nilai Text Area dahulu
           
      isiTextAreaAsli.setText("");
      
        for (int i = awal; i >= akhir; i++) {
          
                        if (i %10 == 0){
            
            isiTextAreaAsli.append(String.valueOf(i) + "\n");
            
                        }
            
        }
             
  
    }//GEN-LAST:event_btnAsliActionPerformed

    private void btnGenapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenapActionPerformed
        // TODO add your handling code here:
        
      int awal = 10;
      int akhir = 100;
      
     
      //bersihkan nilai Text Area dahulu
                       
      for (int i = awal; akhir >= i; i++) {
            
            if (i %10 == 0){
          
            jTextAreaGenap.append(String.valueOf(i) + "\n");
            
            }
        }
        
      

      
    }//GEN-LAST:event_btnGenapActionPerformed

    private void btnGanjilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanjilActionPerformed
        // TODO add your handling code here:
        
      int awal = Integer.parseInt(bilGanjil1.getText());
      int akhir = Integer.parseInt(bilGanjil2.getText());
      
      if(awal>akhir)
      {
          int temp = awal;
          awal = akhir;
          akhir = temp;
             
              }
      
      //bersihkan nilai Text Area dahulu
           
      isiTextAreaGanjil.setText("");
      
        for (int i = awal; i <= akhir; i++) {
            
            if (i %2 != 10){
          
            isiTextAreaGanjil.append(String.valueOf(i) + " ");
            
            }
        }
        
    }//GEN-LAST:event_btnGanjilActionPerformed

    private void bilGenap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilGenap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilGenap1ActionPerformed

    private void bilGenap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilGenap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilGenap2ActionPerformed

    private void isiTextAreaAsliInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_isiTextAreaAsliInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_isiTextAreaAsliInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariDeret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariDeret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariDeret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariDeret.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariDeret().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bilAsli1;
    private javax.swing.JTextField bilAsli2;
    private javax.swing.JTextField bilGanjil1;
    private javax.swing.JTextField bilGanjil2;
    private javax.swing.JTextField bilGenap1;
    private javax.swing.JTextField bilGenap2;
    private javax.swing.JButton btnAsli;
    private javax.swing.JButton btnGanjil;
    private javax.swing.JButton btnGenap;
    private javax.swing.JTextArea isiTextAreaAsli;
    private javax.swing.JTextArea isiTextAreaGanjil;
    private javax.swing.JScrollPane isiTextAreaGenap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextArea jTextAreaGenap;
    private javax.swing.JScrollPane textAreaAsli;
    private javax.swing.JScrollPane textAreaGanjil;
    // End of variables declaration//GEN-END:variables
}
