/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktek;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LatFrame_8_Desktop_External extends javax.swing.JFrame {

    /**
     * Creates new form LatFrame_8_App2_Internal
     */
    public LatFrame_8_Desktop_External() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPW = new javax.swing.JDialog();
        txUser = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        txPW = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        dpUtama = new javax.swing.JDesktopPane();
        mnBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        mnuBukaAplikasi1 = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dialogPW.setMinimumSize(new java.awt.Dimension(300, 250));

        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btExit.setText("Exit");

        jLabel1.setText("Username ");

        jLabel2.setText("Password");

        javax.swing.GroupLayout dialogPWLayout = new javax.swing.GroupLayout(dialogPW.getContentPane());
        dialogPW.getContentPane().setLayout(dialogPWLayout);
        dialogPWLayout.setHorizontalGroup(
            dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPWLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExit)
                    .addGroup(dialogPWLayout.createSequentialGroup()
                        .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dialogPWLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPWLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)))
                            .addGroup(dialogPWLayout.createSequentialGroup()
                                .addComponent(btLogin)
                                .addGap(24, 24, 24)))
                        .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txUser)
                            .addComponent(txPW, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        dialogPWLayout.setVerticalGroup(
            dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPWLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(dialogPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin)
                    .addComponent(btExit))
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.GroupLayout dpUtamaLayout = new javax.swing.GroupLayout(dpUtama);
        dpUtama.setLayout(dpUtamaLayout);
        dpUtamaLayout.setHorizontalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        dpUtamaLayout.setVerticalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        MenuFile.setText("File");

        mnuBukaAplikasi1.setText("Buka Aplikasi 1");
        mnuBukaAplikasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBukaAplikasi1ActionPerformed(evt);
            }
        });
        MenuFile.add(mnuBukaAplikasi1);

        mnExit.setText("Exit");
        MenuFile.add(mnExit);

        mnBar.add(MenuFile);

        jMenu2.setText("Edit");
        mnBar.add(jMenu2);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpUtama)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpUtama)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuBukaAplikasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBukaAplikasi1ActionPerformed
        // TODO add your handling code here:
        
          if(!(ifrAplikasi1.isVisible())){
            
            this.dpUtama.add(ifrAplikasi1);
            
            ifrAplikasi1.setVisible(true);
            
        }
        
        else {
            
            JOptionPane.showMessageDialog(this,"Aplikasi 1 sudah dibuka");
            
        }
        
        
        
    }//GEN-LAST:event_mnuBukaAplikasi1ActionPerformed

    
    private LatFrame_8_App1_Internal ifrAplikasi1;
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        this.mnBar.setVisible(false);
        this.mnuBukaAplikasi1.setVisible(false);
        dialogPW.setLocationRelativeTo(this);
        dialogPW.setVisible(true);
        
        ifrAplikasi1 = new LatFrame_8_App1_Internal();
        
    }//GEN-LAST:event_formComponentShown

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        
        String pass=txPW.getText();
        String user=txUser.getText();
        
        if (pass.equals("sif upj")&&user.equals("sif upj")) {
            
            this.mnBar.setVisible(true);
            this.mnuBukaAplikasi1.setVisible(true);
            this.dialogPW.setVisible(false);
            
        }
        
        else {
            
            JOptionPane.showMessageDialog(this, "Error");
            
        }
        
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatFrame_8_Desktop_External.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatFrame_8_Desktop_External.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatFrame_8_Desktop_External.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatFrame_8_Desktop_External.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatFrame_8_Desktop_External().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogin;
    private javax.swing.JDialog dialogPW;
    private javax.swing.JDesktopPane dpUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnuBukaAplikasi1;
    private javax.swing.JPasswordField txPW;
    private javax.swing.JTextField txUser;
    // End of variables declaration//GEN-END:variables
}
