/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktek;

/**
 *
 * @author User
 */

import javax.swing.JOptionPane;


public class LatJDPane extends javax.swing.JFrame {

    /**
     * Creates new form LatJDPane
     */
    public LatJDPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpUtama = new javax.swing.JDesktopPane();
        ifrAplikasi1 = new javax.swing.JInternalFrame();
        btnKeluar = new javax.swing.JButton();
        mnuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuBukaAplikasi1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        ifrAplikasi1.setTitle("Aplikasi 1");
        ifrAplikasi1.setVisible(true);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifrAplikasi1Layout = new javax.swing.GroupLayout(ifrAplikasi1.getContentPane());
        ifrAplikasi1.getContentPane().setLayout(ifrAplikasi1Layout);
        ifrAplikasi1Layout.setHorizontalGroup(
            ifrAplikasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifrAplikasi1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );
        ifrAplikasi1Layout.setVerticalGroup(
            ifrAplikasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifrAplikasi1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        javax.swing.GroupLayout dpUtamaLayout = new javax.swing.GroupLayout(dpUtama);
        dpUtama.setLayout(dpUtamaLayout);
        dpUtamaLayout.setHorizontalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpUtamaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(ifrAplikasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        dpUtamaLayout.setVerticalGroup(
            dpUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpUtamaLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(ifrAplikasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        dpUtama.setLayer(ifrAplikasi1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        mnuBukaAplikasi1.setText("Buka Aplikasi 1");
        mnuBukaAplikasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBukaAplikasi1ActionPerformed(evt);
            }
        });
        jMenu1.add(mnuBukaAplikasi1);

        mnuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        mnuBar1.add(jMenu2);

        setJMenuBar(mnuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpUtama)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpUtama)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed

        ifrAplikasi1.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void mnuBukaAplikasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBukaAplikasi1ActionPerformed
        // TODO add your handling code here:
        
        if(!(ifrAplikasi1.isVisible())){
            
            this.dpUtama.add(ifrAplikasi1);
            
            ifrAplikasi1.setVisible(true);
            
        }
        
        else {
            
            JOptionPane.showMessageDialog(this,"Aplikasi 1 sudah dibuka");
            
        }
        
    }//GEN-LAST:event_mnuBukaAplikasi1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        ifrAplikasi1.dispose();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatJDPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatJDPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatJDPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatJDPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatJDPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JDesktopPane dpUtama;
    private javax.swing.JInternalFrame ifrAplikasi1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mnuBar1;
    private javax.swing.JMenuItem mnuBukaAplikasi1;
    // End of variables declaration//GEN-END:variables
}
